name: Run Python Script in Multiple Repos

on:
  workflow_run:
    workflows: ["Run Python Script"]
    types:
      - completed
  # schedule:
  #   - cron: '0 0 1 */3 *' 
  workflow_dispatch: {}

jobs:
  run_scripts:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repository: ["projectwilsen/test1.git", "https://github.com/projectwilsen/test2.git"]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        repository: ${{ matrix.repository }}
        path: external-repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Choose the desired Python version

    # - name: Create Virtual Environment
    #   run: |
    #     python -m venv venv
    #     source venv/bin/activate

    # - name: Install Dependencies
    #   run: |
    #     cd external-repository
    #     pip install -r path/to/your/requirements.txt

    - name: Run Python Script
      run: |
        cd external-repository
        python main.py
